### ISSUE TITLE
Insert example shim

### ISSUE THREAD

**Issue by jimhester** [r-pkgs/pkgload#13]
<a href="https://github.com/hadley"><img src="https://avatars0.githubusercontent.com/u/4196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hadley](https://github.com/hadley)**
_Thursday May 28, 2015 at 16:21 GMT_
_Originally opened as https://github.com/hadley/devtools/issues/821_

----

So you don't need to build and reload to run examples

**Comment by Dasonk** [comment]
Is anybody working on this at the moment? I can see how this would be done but don't want to fork and implement if it's being worked on.

**Comment by jimhester** [comment]
You are welcome to give it a shot if you would like to!

**Comment by jimhester** [comment]
`dev_example()` seems to close this. (2d57b3c102f62573dd47e4241489431efbf854bd)
