### ISSUE TITLE
Can't load downstream packages after load_all()

### ISSUE THREAD

**Issue by jimhester** [r-pkgs/pkgload#16]
<a href="https://github.com/pitakakariki"><img src="https://avatars3.githubusercontent.com/u/1023705?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pitakakariki](https://github.com/pitakakariki)**
_Monday Jan 25, 2016 at 00:43 GMT_
_Originally opened as https://github.com/hadley/devtools/issues/1045_

----

In the working directory of a project based on a local fork of https://github.com/lme4/lme4:

``` r
> devtools::load_all()
Loading lme4
Loading required package: Matrix
> library(MEMSS)
Error: package ‘lme4’ required by ‘MEMSS’ could not be found
```

The error is thrown from `base::.getRequiredPackages2`, because it can't work out the version of the package loaded by `devtools::load_all`. The function `.findVersion` is defined inside `base::getRequiredPackages2`:

``` r
    .findVersion <- function(pkg, lib.loc = NULL) {
        pfile <- system.file("Meta", "package.rds", package = pkg, 
            lib.loc = lib.loc)
        if (nzchar(pfile)) 
            as.numeric_version(readRDS(pfile)$DESCRIPTION["Version"])
    }
```

It's not finding `package.rds`, so it's returning `NULL`. This triggers the error here:

``` r
        current <- .findVersion(pkg, lib.loc)
        if (is.null(current)) 
            stop(gettextf("package %s required by %s could not be found", 
                sQuote(pkg), sQuote(pkgname)), call. = FALSE, 
                domain = NA)
```

**Comment by jimhester** [comment]
<a href="https://github.com/jimhester"><img src="https://avatars0.githubusercontent.com/u/205275?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jimhester](https://github.com/jimhester)**
_Friday Jan 29, 2016 at 14:52 GMT_

----

If this was using `utils::packageVersion()` as the comment suggests [wch/r-source/src/library/base/R/library.R#L812-L826](https://github.com/wch/r-source/blob/f5e8102b51880ce89dfd3395a48066c5794fc06b/src/library/base/R/library.R#L812-L826) this would work fine. But as you noted because `load_all()` does not create a `package.rds` file this breaks.

We could insert a shim `.getRequiredPackages2` in devtools to fix this I suppose although I think it is best to keep shims to a minimum...

**Comment by jimhester** [comment]
In general we cannot fix this error with shims, the error is coming from the `library()` call, so even if we have a shim for `getRequiredPackages2` in lme4's namespace it won't be called. You would have to do something like `testthat::with_mock` used to do and replace the function pointer, but that causes issues with the byte compiler.

**Comment by bbolker** [comment]
Can anyone comment on the circumstances under which this occurs, and whether there are workarounds (other than simply installing the dev version of the package rather than trying to use `load_all()`?  I am experiencing it with the `lme4`/`gamm4` combination. Is there something special about `lme4`, or is this just the first time I've noticed the problem?
