### ISSUE TITLE
FR: load_all() should check imports

### ISSUE THREAD

**Issue by jimhester** [r-pkgs/pkgload#18]
<a href="https://github.com/krlmlr"><img src="https://avatars3.githubusercontent.com/u/1741643?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [krlmlr](https://github.com/krlmlr)**
_Monday Aug 29, 2016 at 19:40 GMT_
_Originally opened as https://github.com/hadley/devtools/issues/1311_

----

Can `load_all()` check if a `NAMESPACE` import is also declared in `DESCRIPTION`?

https://github.com/klutometis/roxygen/issues/429#issuecomment-243230990

**Comment by jimhester** [comment]
<a href="https://github.com/hadley"><img src="https://avatars0.githubusercontent.com/u/4196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hadley](https://github.com/hadley)**
_Thursday Nov 03, 2016 at 16:50 GMT_

----

This would require quite a bit of NAMESPACE parsing, so I'm not sure it's worth the effort.

**Comment by jimhester** [comment]
<a href="https://github.com/krlmlr"><img src="https://avatars3.githubusercontent.com/u/1741643?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [krlmlr](https://github.com/krlmlr)**
_Friday Nov 04, 2016 at 00:00 GMT_

----

I've seen at least one case where a package loaded with load_all() that didn't declare an import in DESCRIPTION couldn't use that import. That also helps, but is not very nice.

The following code is a first approximation (use `ns_env()` inside `devtools`):

``` r
asNamespace("devtools") %>%
  parent.env() %>%
  as.list %>%
  lapply(environment) %>%
  purrr::compact() %>%
  vapply(getPackageName, character(1)) %>%
  unique
```

**Comment by jimhester** [comment]
This will do it, not sure it should really be in `load_all()` though, we don't do any other checks like this or issue warnings there currently. roxygen already depends on desc, so you can do a similar check there pretty easily by using `desc::desc_get_deps()` in place of `parse_deps()`.

```r
undeclared_namespace_imports <- function(pkg = ".") {
  pkg <- as.package(pkg)

  import_packages <- names(getNamespaceImports(pkg$package))

  setdiff(import_packages, c("base", parse_deps(pkg$depends)$name, parse_deps(pkg$imports)$name))
}
```

cc @krlmlr

**Comment by krlmlr** [comment]
Actually, roxygen2 could just update the imports as part of the namespace roclet. This was considered unsafe before, but now we have desc it should be fine.?
