### ISSUE TITLE
SetClassUnion errors in run_examples

### ISSUE THREAD

**Issue by jimhester** [r-pkgs/pkgload#22]
<a href="https://github.com/flying-sheep"><img src="https://avatars3.githubusercontent.com/u/291575?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [flying-sheep](https://github.com/flying-sheep)**
_Friday Oct 07, 2016 at 11:42 GMT_
_Originally opened as https://github.com/hadley/devtools/issues/1372_

----

Seems like #168 resurfaced when running `run_examples` twice or having the package in question loaded

**Comment by hadley** [comment]
https://github.com/hadley/devtools/issues/168

**Comment by jimhester** [comment]
I can't reproduce this error, `devtools::run_examples()` works fine on the [devel version of destiny](https://github.com/Bioconductor-mirror/destiny/commit/a4ac85018dc6a20b6f85c588904301604ed0f310) regardless of number of times I run it.
