### ISSUE TITLE
Warning about exported but not-in-namespace objects

### ISSUE THREAD

**Issue by krlmlr** [r-pkgs/pkgload#31]
This never happened before, perhaps related to #30?

``` r
withr::with_dir(
  {dir.create(dir <- tempfile()); dir},
  {
    system("git clone https://github.com/rstats-db/DBI.git", intern = TRUE)
    pkgload::load_all("DBI", quiet = TRUE)
  }
)
#> Warning in setup_ns_exports(pkg, export_all): Objects listed as exports,
#> but not present in namespace: show
```

**Comment by jimhester** [comment]
Should be fixed by https://github.com/r-pkgs/pkgload/commit/764dcda25431012366f64bc4120ede589731aefc

**Comment by krlmlr** [comment]
Thanks, works for me. Just curious: why did you change the title of the issue?

**Comment by jimhester** [comment]
Because the warning is not actually bogus, `show` is exported but not in the package namespace.
