### ISSUE TITLE
Unloading shared library doesn't seem to work

### ISSUE THREAD

**Issue by krlmlr** [r-pkgs/pkgload#5]
I've noticed I have to restart R with the new toolchain; simply running load_all() seems to keep using the old shared library (on Ubuntu).

**Comment by jimhester** [comment]
I think this was a side effect of https://github.com/r-pkgs/pkgbuild/pull/1, as `needs_compile()` was always returning FALSE, so [`compile_dll()`](https://github.com/r-pkgs/pkgbuild/blob/master/R/compile-dll.r#L21-L22) was exiting early.
